server:
  port: 8085

quantum:
  python-executable: D:/miniconda3_python/envs/quantum/python.exe
  local-script-path: python/grover.py
  ibm-script-path: python/grover_ibm.py
  ibm-token: "PASTE_YOUR_IBM_TOKEN_HERE"
  execution-mode: LOCAL # or IBM